# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mark_it_up}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Baptiste Grenier"]
  s.date = %q{2010-11-03}
  s.description = %q{Mark It Up editor integration for rails 3, all the real work is done by the code from http://github.com/cingel/mark_it_up}
  s.email = %q{baptiste@bapt.name}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/generators/miu_controller_generator.rb",
     "lib/generators/templates/app/controllers/mark_it_up_controller.rb",
     "lib/generators/templates/app/views/mark_it_up/preview.html.erb",
     "lib/mark_it_up.rb",
     "lib/mark_it_up/view_helpers.rb",
     "lib/public/mark_it_up/icons/bold.png",
     "lib/public/mark_it_up/icons/book_arrow.png",
     "lib/public/mark_it_up/icons/button.png",
     "lib/public/mark_it_up/icons/clean.png",
     "lib/public/mark_it_up/icons/code.png",
     "lib/public/mark_it_up/icons/h1.png",
     "lib/public/mark_it_up/icons/h2.png",
     "lib/public/mark_it_up/icons/h3.png",
     "lib/public/mark_it_up/icons/h4.png",
     "lib/public/mark_it_up/icons/h5.png",
     "lib/public/mark_it_up/icons/h6.png",
     "lib/public/mark_it_up/icons/image.png",
     "lib/public/mark_it_up/icons/italic.png",
     "lib/public/mark_it_up/icons/link.png",
     "lib/public/mark_it_up/icons/list-bullet.png",
     "lib/public/mark_it_up/icons/list-item.png",
     "lib/public/mark_it_up/icons/list-numeric.png",
     "lib/public/mark_it_up/icons/paragraph.png",
     "lib/public/mark_it_up/icons/picture.png",
     "lib/public/mark_it_up/icons/preview.png",
     "lib/public/mark_it_up/icons/stroke.png",
     "lib/public/mark_it_up/jquery.markitup.js",
     "lib/public/mark_it_up/jquery.markitup.pack.js",
     "lib/public/mark_it_up/skins/markitup/images/bg-container.png",
     "lib/public/mark_it_up/skins/markitup/images/bg-editor-bbcode.png",
     "lib/public/mark_it_up/skins/markitup/images/bg-editor-dotclear.png",
     "lib/public/mark_it_up/skins/markitup/images/bg-editor-html.png",
     "lib/public/mark_it_up/skins/markitup/images/bg-editor-json.png",
     "lib/public/mark_it_up/skins/markitup/images/bg-editor-markdown.png",
     "lib/public/mark_it_up/skins/markitup/images/bg-editor-textile.png",
     "lib/public/mark_it_up/skins/markitup/images/bg-editor-wiki.png",
     "lib/public/mark_it_up/skins/markitup/images/bg-editor-xml.png",
     "lib/public/mark_it_up/skins/markitup/images/bg-editor.png",
     "lib/public/mark_it_up/skins/markitup/images/handle.png",
     "lib/public/mark_it_up/skins/markitup/images/menu.png",
     "lib/public/mark_it_up/skins/markitup/images/submenu.png",
     "lib/public/mark_it_up/skins/markitup/style.css",
     "lib/public/mark_it_up/skins/simple/images/handle.png",
     "lib/public/mark_it_up/skins/simple/images/menu.png",
     "lib/public/mark_it_up/skins/simple/images/submenu.png",
     "lib/public/mark_it_up/skins/simple/style.css",
     "mark_it_up.gemspec"
  ]
  s.homepage = %q{http://github.com/gwarf/mark_it_up}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Mark It Up integration for rails}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

